### ISSUE TITLE
debug output isn't fully marshaled to JSON

### ISSUE THREAD

**Issue by alexeagle** [songkeys/tswc#1]
My use case is to convert to .swcrc but use the original `swc` compiler tool (the bare Rust binary without the node CLI binding, since it's much faster to startup). So I really only want a CLI for tsconfig-to-swcconfig by itself. Following https://github.com/Songkeys/tsconfig-to-swcconfig/issues/9 led me here.

Running with `tsconfig.json` containing

```
{
    "compilerOptions": {
        "target": "ES2017",
        "module": "AMD"
    }
}
```

version 1.1.1 produces

```
$ tswc --debug
{
  ...
    transform: {
      legacyDecorator: true,
      decoratorMetadata: false,
      react: [Object]
    },
```

Then of course you can't use the resulting file with `swc` because of the bad `[Object]` syntax in there.

**Comment by alexeagle** [comment]
Oh, of course it's much worse than that, the output isn't JSON at all, the keys aren't quoted.
Could you add some way to use this tool simply to produce the JSON output? Or, would you be willing to take a PR to `tsconfig-to-swcconfig` to add a minimal CLI there?

**Comment by songkeys** [comment]
Hi Alex. Sorry for the late reply. I was on vacation. Thank you for your report.

You can write a script using `tsconfig-to-swcconfig` in your use case I think. That's not hard.

> Could you add some way to use this tool simply to produce the JSON output?

Sure. This is reasonable. I'll do it later.

> Or, would you be willing to take a PR to tsconfig-to-swcconfig to add a minimal CLI there?

Of course. I'm happy to take this PR.

**Comment by songkeys** [comment]
This is fixed in https://github.com/Songkeys/tswc/commit/441c74a069f996cc3d8149e1e693db407f63a040 , published in v1.1.2. Now it outputs standard json in debug mode.

I'll close this issue. Let's meet in that PR if you are willing to. Take your time.

**Comment by alexeagle** [comment]
That's awesome that you picked this up, thank you!

There's still an issue though, the stdout contains non-json lines at the beginning and end, those should probably go to stderr instead.

```
[debug] swcrc:
{
  "sourceMaps": "inline",
  "module": {
...
> swc  --config-file /Users/alexeagle/Projects/bazel-examples/react-cra/.swcrc_from_tsconfig2459905792
```

so it can't just be run like `tswc --debug > .swcrc`

**Comment by alexeagle** [comment]
OH, you made a new CLI! Perfect, now we can fix up Bazel https://github.com/aspect-build/rules_swc/pull/206

**Comment by songkeys** [comment]
Yes. I made a new CLI in `tsconfig-to-swcconfig` for *conversion*. `tswc` is mainly for *compiling*. Let me if I missed anything :)
